fws:
- fw_id: 1
  spec:
    _tasks:
    - _fw_name: ScriptTask
      script: python /home/mu2so4/univ/disser/cwl-pure/task1.py /home/mu2so4/univ/disser/hpc2c-seismics/segy/00000215_276_22_14.18.0.sgy 15 30 20 filtered2.sd
    - _fw_name: FileTransferTask
      files:
      - src: filtered2.sd
        dest: /home/mu2so4/univ/disser/cwl-pure/fireworks/outputs/filtered2.sd
      mode: copy
- fw_id: 2
  spec:
    _tasks:
    - _fw_name: ScriptTask
      script: python /home/mu2so4/univ/disser/cwl-pure/task2.py /home/mu2so4/univ/disser/cwl-pure/fireworks/outputs/filtered2.sd 40 50 out_fin.png filtered.segy
    - _fw_name: FileTransferTask
      dest: /home/mu2so4/univ/disser/cwl-pure/fireworks/outputs/
      files:
      - out_fin.png
      - filtered.segy
      mode: move
links:
  1:
  - 2
metadata: {}
