name: Test cwltool (CWL reference implementation) Run

on:
  workflow_run:
    workflows: [Test Native Workflow Run (No WMS)]
    types:
      - completed
    branches: [main, feature/*]

jobs:
  native:
    name: CWL (native)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run CWLTool native
        run: |
          chmod +x cwltool/run.sh
          ./cwltool/run.sh

  docker:
    name: CWL (Docker)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run CWLTool in Docker
        run: |
          chmod +x cwltool/run-docker.sh
          ./cwltool/run-docker.sh

  apptainer:
    name: CWL (Apptainer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Run CWLTool in Apptainer
        run: |
          chmod +x cwltool/run-singularity.sh
          ./cwltool/run-singularity.sh

