name: Test Workflow Benchmarking

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  download-data:
    name: Prepare seismic data
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-key.outputs.cache-key }}
    steps:
      - name: Set output key
        id: set-key
        run: echo "cache-key=seismic-input-cache" >> $GITHUB_OUTPUT

      - name: Cache seismic input
        id: cache
        uses: actions/cache@v4
        with:
          path: inputs/input.sgy
          key: ${{ steps.set-key.outputs.cache-key }}
          
      - name: Download seismic input file
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p inputs
          curl -L --insecure -o inputs/input.sgy https://hu-cloud.sscc.ru/index.php/s/cyGHnWZsb5FEJQj/download/00000215_276_22_14.18.0.sgy

      - name: Save to workspace
        uses: actions/upload-artifact@v4
        with:
          name: seismic-input
          path: inputs/input.sgy
          retention-days: 7

  native:
    name: Containerless run
    needs: download-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [native, cwltool, fireworks, luigi, nextflow, parsl, snakemake]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh benchmarks/${{ matrix.wms }}/benchmark.sh
          ./benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/benchmark.sh

  docker:
    name: Docker run
    needs: download-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [native, cwltool]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh benchmarks/${{ matrix.wms }}/benchmark.sh
          ./benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/benchmark-docker.sh

  apptainer:
    name: Apptainer run
    needs: download-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [native, cwltool, nextflow, snakemake]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Run ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh benchmarks/${{ matrix.wms }}/benchmark-singularity.sh
          ./benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/benchmark-singularity.sh
          
  full-benchmark:
    name: Full Benchmark Run and Summary
    needs: [native, docker, apptainer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Run Full Benchmark and Summarize
        run: |
          chmod +x benchmark-full.sh
          ./benchmark-full.sh
          
      - name: Save table summary
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary/summary.csv
          retention-days: 7
          
      - name: Save average times
        uses: actions/upload-artifact@v4
        with:
          name: average-times
          path: summary/avg_times.png
          retention-days: 7
          
      - name: Save speedups
        uses: actions/upload-artifact@v4
        with:
          name: speedups
          path: summary/speedups.png
          retention-days: 7

