name: Test Luigi Run

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  download-data:
    name: Prepare seismic data
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-key.outputs.cache-key }}
    steps:
      - name: Set output key
        id: set-key
        run: echo "cache-key=seismic-input-cache" >> $GITHUB_OUTPUT

      - name: Download seismic input file
        run: |
          mkdir -p inputs
          curl -L --insecure -o inputs/input.sgy https://hu-cloud.sscc.ru/index.php/s/cyGHnWZsb5FEJQj/download/00000215_276_22_14.18.0.sgy

      - name: Save to workspace
        uses: actions/upload-artifact@v4
        with:
          name: seismic-input
          path: inputs/input.sgy
          retention-days: 7

  native:
    name: Simple Luigi run
    needs: download-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run native workflow
        run: |
          chmod +x benchmarks/luigi/init.sh benchmarks/luigi/run.sh
          ./benchmarks/luigi/init.sh
          ./benchmarks/luigi/run.sh

