name: Test Workflow Run

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  download-data:
    name: Prepare seismic data
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-key.outputs.cache-key }}
    steps:
      - name: Set output key
        id: set-key
        run: echo "cache-key=seismic-input-cache" >> $GITHUB_OUTPUT

      - name: Download seismic input file
        run: |
          mkdir -p inputs
          curl -L --insecure -o inputs/input.sgy https://hu-cloud.sscc.ru/index.php/s/cyGHnWZsb5FEJQj/download/00000215_276_22_14.18.0.sgy

      - name: Save to workspace
        uses: actions/upload-artifact@v4
        with:
          name: seismic-input
          path: inputs/input.sgy
          retention-days: 7
          
  install-only:
    name: Only installation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [airflow, dask]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/init.sh

  native:
    name: Containerless run
    needs: download-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [native, cwltool, fireworks, luigi, nextflow, parsl, snakemake]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh benchmarks/${{ matrix.wms }}/run.sh
          ./benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/run.sh

  docker:
    name: Docker run
    needs: download-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [native, cwltool]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - name: Run ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh benchmarks/${{ matrix.wms }}/run.sh
          ./benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/run-docker.sh

  apptainer:
    name: Apptainer run
    needs: download-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wms: [native, cwltool, nextflow, snakemake]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v4
        with:
          name: seismic-input
          path: inputs

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Run ${{ matrix.wms }} workflow
        run: |
          chmod +x benchmarks/${{ matrix.wms }}/init.sh benchmarks/${{ matrix.wms }}/run-singularity.sh
          ./benchmarks/${{ matrix.wms }}/init.sh
          ./benchmarks/${{ matrix.wms }}/run-singularity.sh

